# Generated by Django 6.0.3 on 2026-03-12 22:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Зображення')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія товарів',
                'verbose_name_plural': 'Категорії товарів',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('form_location', models.CharField(default='hero', max_length=60, verbose_name='Форма')),
                ('utm_source', models.CharField(blank=True, default='', max_length=200)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=200)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=200)),
                ('utm_content', models.CharField(blank=True, default='', max_length=200)),
                ('utm_term', models.CharField(blank=True, default='', max_length=200)),
                ('gclid', models.CharField(blank=True, default='', max_length=200, verbose_name='Google Click ID')),
                ('fbclid', models.CharField(blank=True, default='', max_length=200, verbose_name='Facebook Click ID')),
                ('bitrix_lead_id', models.CharField(blank=True, default='', max_length=20, verbose_name='ID ліда у Bitrix24')),
                ('status', models.CharField(choices=[('pending', 'В обробці'), ('sent', 'Відправлено'), ('failed', 'Помилка')], default='pending', max_length=10, verbose_name='Статус')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('referrer', models.URLField(blank=True, default='', max_length=500, verbose_name='Referrer')),
                ('page_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL сторінки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_phone', models.CharField(default='+38 067 611 96 22', max_length=30, verbose_name='Телефон у хедері')),
                ('header_cta_text', models.CharField(default='Отримати консультацію', max_length=60, verbose_name='Текст кнопки хедеру')),
                ('hero_title', models.CharField(default='ДОСТАВКА ВАНТАЖУ З КИТАЮ', max_length=120, verbose_name='Заголовок hero')),
                ('hero_subtitle', models.CharField(default='7–10 днів • від $5,95/кг • з гарантією строків', max_length=120, verbose_name='Підзаголовок hero')),
                ('hero_description', models.TextField(default='Знижуємо ваші логістичні витрати до 20% за рахунок прямої консолідації на власних складах у Китаї та оптимізації маршрутів без посередників.', verbose_name='Опис hero')),
                ('hero_benefits', models.TextField(default='Без прихованих платежів.\nБез затримок.\nБез ризиків.', verbose_name='Переваги під описом (кожна з нового рядка)')),
                ('hero_form_title', models.CharField(default='Дізнайтесь, скільки можна зекономити на доставці з Китаю', max_length=120, verbose_name='Заголовок форми hero')),
                ('hero_form_subtitle', models.CharField(default='Розрахуємо кращий тариф та оптимальну модель поставки', max_length=160, verbose_name='Підзаголовок форми hero')),
                ('stats_companies', models.CharField(default='5000+', max_length=20, verbose_name='Кількість компаній')),
                ('stats_years', models.CharField(default='2009', max_length=20, verbose_name='Рік заснування')),
                ('cta_1_title', models.CharField(default='Готові знизити витрати на доставку та уникнути ризиків?', max_length=160, verbose_name='CTA банер 1 — заголовок')),
                ('cta_1_text', models.TextField(default='Залиште заявку — логістичний експерт прорахує оптимальний маршрут, покаже, де можна зекономити, та підбере формат доставки без прихованих платежів і затримок.', verbose_name='CTA банер 1 — текст')),
                ('cta_2_title', models.CharField(default='Дізнайтесь, скільки ви реально можете зекономити на доставці з Китаю', max_length=160, verbose_name='CTA банер 2 — заголовок')),
                ('cta_2_text', models.CharField(default='Отримаєте персональний розрахунок та варіанти оптимізації маршруту з фіксованими строками', max_length=200, verbose_name='CTA банер 2 — підзаголовок')),
                ('contact_form_title', models.CharField(default='Залишились запитання або хочете оформити замовлення?', max_length=120, verbose_name='Заголовок форми контактів')),
                ('contact_form_subtitle', models.CharField(default='Заповніть форму та отримайте консультацію логістичного експерта', max_length=200, verbose_name='Підзаголовок форми контактів')),
                ('footer_phone', models.CharField(default='+38 067 611 96 22', max_length=30, verbose_name='Телефон у футері')),
                ('footer_email', models.EmailField(default='info@wingo.com.ua', max_length=254, verbose_name='Email у футері')),
                ('footer_address', models.CharField(default='Україна, Київ', max_length=200, verbose_name='Адреса')),
                ('footer_telegram', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('footer_viber', models.URLField(blank=True, default='', verbose_name='Viber')),
                ('footer_instagram', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('footer_facebook', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('footer_linkedin', models.URLField(blank=True, default='', verbose_name='LinkedIn')),
                ('footer_copyright', models.CharField(default='© 2009–2025 WINGO. Всі права захищені.', max_length=200, verbose_name='Copyright')),
                ('gtm_container_id', models.CharField(blank=True, default='', max_length=20, verbose_name='GTM Container ID')),
                ('bitrix_webhook_url', models.CharField(blank=True, default='', help_text='https://your-domain.bitrix24.ua/rest/{user_id}/{webhook_code}', max_length=500, verbose_name='Bitrix24 Webhook URL')),
                ('ai_calculator_url', models.URLField(blank=True, default='https://wingo.com.ua/', verbose_name='URL AI-калькулятора')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
            },
        ),
    ]
