# Generated by Django 6.0.2 on 2026-03-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Доставка вантажу з Китаю', max_length=120, verbose_name='Заголовок hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stats_companies',
            field=models.CharField(default='5000', max_length=20, verbose_name='Кількість компаній'),
        ),
    ]
